### PR TITLE
䷅Feature/auto conf🐭

### PR DESCRIPTION
**Pull request by mabulgu**

### CODE REVIEW

**Comment by mabulgu** [comment]
@springdo Can you review this if you don't mind? If not, I can ask sbd else:)

**Comment by mabulgu** [comment]
@springdo Can you also check if the configuration is the right one btw? 

And another thing: should we add a system-test to check the configuration within so? what do you think @gkmahendran09 @springdo ?

**Review by springdo — APPROVED** [review]
LGTM

**Comment by mabulgu** [comment]
Thanks👋

**Pull request merged**
